### ISSUE TITLE
Sign up page

### ISSUE THREAD

**Issue by Samirahajiragab** [Samirahajiragab/saas-website#3]
<img width="592" alt="image" src="https://user-images.githubusercontent.com/55094325/79878838-e60dab80-83bb-11ea-85ad-b9772cefa13c.png">

  this how i want to end up 
<img width="490" alt="image" src="https://user-images.githubusercontent.com/55094325/79867399-498fdd00-83ac-11ea-9ce2-7c9ee549980c.png">
 Please help!
@muxlowc
@mackenzierose

**Comment by muxlowc** [comment]
@Samirahajiragab 

1) You're likely going to have to use grid-stretch / unit-content-distribute / content-fill & -shrink (https://learn-the-web.algonquindesign.ca/topics/gridifier-cheat-sheet/#unit-utilities)- I find that sometimes when using embed images with a grid, that it doesn't work too well, so you could remove the embed classes and use img-flex and sizing instead :)

2) I think you have a class on your "email" "password" etc classes, so remove those from the divs surrounding your input/labels, and I think you have a class of l-1-2 where it should be l-1 instead

3) add width 100% to your btn-blue

**Comment by Samirahajiragab** [comment]
1.I don't know why is it saying this i checked for open tags i don't seem to see it?
<img width="415" alt="image" src="https://user-images.githubusercontent.com/55094325/79937298-7d5c1880-8427-11ea-998d-9d61feba615e.png">
<img width="415" alt="image" src="https://user-images.githubusercontent.com/55094325/79937413-c9a75880-8427-11ea-8110-93b9cdc5a509.png">

2.Why is saying this?
<img width="461" alt="image" src="https://user-images.githubusercontent.com/55094325/79937436-daf06500-8427-11ea-90b8-ba327906dab9.png">

 3. why is saying this?
<img width="487" alt="image" src="https://user-images.githubusercontent.com/55094325/79937818-e09a7a80-8428-11ea-8c71-08d88fc9c162.png">

4. Don't understand this
<img width="507" alt="image" src="https://user-images.githubusercontent.com/55094325/79939647-9bc51280-842d-11ea-852c-f27c1f67cfdd.png">


Thank you so much for tips it was soo useful! :) 
but the logo is not centered 
<img width="507" alt="image" src="https://user-images.githubusercontent.com/55094325/79938044-78986400-8429-11ea-9cd3-b7387a479072.png">


@muxlowc

**Comment by muxlowc** [comment]
@Samirahajiragab 

1) Your footer should go inside of your `<body>` - body in html does not mean the same as "main" .. body here literally means "all of your code you want on your site goes inside of here" - so therefore all of your content should be inside of your `<body></body>` tags (you'll need to do this for all pages)
- your stray div on your tour page seems to have been fixed too? Looks fine on my end

2) Hm i'm not getting that error on my end - looks good to me - did you maybe at one point have an `<i>` directly inside of a `<ul>`? only <li>s are allowed to be direct children of uls. Let me know though if you are still getting this error

3) You can ignore this one - everyone seems to be getting it for some reason

4) Hmm that issue is worded weirdly lol... but it looks like your nav on your sign-up page is different? You don't seem to have a `<nav>`, which you should have on all pages for accessibility reasons.

5) If you really want to have a different nav for your sign-up page, you can add a class in main.css for adding-left.. technically the text "BeeSurvey" is centered, so you just need to push everything over a bit so it looks like the icon/text are together

**Comment by Samirahajiragab** [comment]
That helped a lot I'm almost done! yay!!
I don't why is saying this even though i have it 
i did had embed, i took it off because it was working well and u told me too
<img width="494" alt="image" src="https://user-images.githubusercontent.com/55094325/79996449-79abae80-8486-11ea-83b0-b08875214566.png">
one last question how can i make the Facebook and Google and Linkedin icon a link whenever someone clicks on it, it takes them to those pages? 

@muxlowc

**Comment by muxlowc** [comment]
@Samirahajiragab  yah you can ignore the embed issues if your figured out another way

2) Hmm okay so, you technically have a label, but you don't actually have any text inside of the `<label>` which is the issue. If you really like the way it looks currently, just rationalize that on you request for grade - but technically it's not very accessible to use placeholders rather than labels (ie. the label above the input should say "first name" and placeholder could say "ie. John")

 Also, another thing I see missing from your form, is you don't currently have type="password" for your password - this is what makes those dots appear.

3) You can just wrap your` <i> `tags inside of an `<a>` tag to make them clickable

**Comment by Samirahajiragab** [comment]
i don't know why is it asking this?<img width="608" alt="image" src="https://user-images.githubusercontent.com/55094325/80016755-8ee20680-84a1-11ea-8627-ec38421fab37.png">

 for the Accessibility testing and checking the browse how i'm suppose do it?
<img width="608" alt="image" src="https://user-images.githubusercontent.com/55094325/80016431-2004ad80-84a1-11ea-8d2d-70a62f052321.png">
<img width="608" alt="image" src="https://user-images.githubusercontent.com/55094325/80016478-2abf4280-84a1-11ea-9653-5ef7293abcf1.png">


@muxlowc

**Comment by muxlowc** [comment]
@Samirahajiragab for the formspree issue, make sure that your form method="POST" (post is in all capital letters) - the email should also be your own (even though it wont work)

For the input/id/name issue, you might need to just add name="(insert word you have for ID)" for all of your inputs (these are usually most important for radio buttons, but I guess markbot wants them :) )

accessibility testing- https://learn-the-web.algonquindesign.ca/topics/accessibility-testing-checklist/ 

browser testing - just test your site on different browsers (safari, opera, firefox, or whatever) and make sure that everything still works. I will be checking on multiple browsers, and I will be manually giving you your mark for that (as well as the accessibility testing) (https://learn-the-web.algonquindesign.ca/topics/browser-testing-checklist/)

**Comment by Samirahajiragab** [comment]
Thank you soo much for all your help!!! Sorry for bothering :)
